import os

# DATA INFORMATION
IMAGE_SIZE = 224
BATCH_SIZE = 1

ROOT_DIR = os.path.abspath('./')
MODEL_DIR = os.path.join(ROOT_DIR, 'MODEL/')
OUT_DIR = os.path.join(ROOT_DIR, 'Resultl/' + 'Misc' + '/')

# RANDOM NUMBER GENERATOR INFORMATION
SEED = 128

# TRAINING INFORMATION
USE_PRETRAINED = True
PRETRAINED = "model1_10.ckpt"
NUM_EPOCHS = 10